### ISSUE TITLE
Move to Puppet 5

### ISSUE THREAD

**Issue by XMol** [KIT-SCC/gridka-xrootd#5]
While updating the code in general for usage with Puppet 5, I'd also like to get rid of some ugly legacy stuff from the CERN ancestor:
* Resource types for managing xrootd configuration files individually are ridiculous.
* Integrate better with systemd.
   * Puppet 5 already does a good job with that. If need be, we can explicitly use [camptocamp/puppet-systemd](https://github.com/camptocamp/puppet-systemd/tree/2.10.0)'s facilities.

**Comment by XMol** [comment]
Involve @maxfischer2781 and @rcaspart

**Comment by maxfischer2781** [comment]
For the GridKa ALICE SE, I did indeed not use the `gridka-xrootd` configuration and systemd features. As far as I can tell, there are only a few issues remaining:

- systemd:
    - Allow for ``[Unit]`` ``After``/``Requires`` (used to start ``frm``, ``purged`` and monitoring alongside ``xrootd``)
    - Various ``[Service]`` ``LimitXXX``/``WorkingDirectory`` (seems to be possible via ``$exports``?)
- configuration:
    - Using a default text template merging in text from hiera seemed simpler 😅 
    - Key-less setting (``ofs.authorize``)

**Comment by XMol** [comment]
### systemd integration

You have two options - irrespective of which Puppet code handles them:
* Write a new service unit file
* Write a [drop-in file](https://github.com/camptocamp/puppet-systemd#drop-in-files)

From the perspective of dCache, both would be equally viable. In case the xrootd rpm ships with a systemd unit file, the latter approach would be more appropriate in my opinion. But afaik that is not the case and we had to marry xrootd/cmsd with systemd ourselves, right?

### configuration

> Key-less setting (ofs.authorize)

I don't know what you want here... As far as I can tell, nothing in this module forces `ofs.authorize` upon you.

> Using a default text template merging in text from hiera seemed simpler

Really? You mean, "using some text that seems to be the same for all our configuration and changing it in bits was much easier"? 😉 Because the templates that are used now hardly make any assumptions and set no defaults. They basically just ensure a specific form for a configuration file, but the content needs to be supplied in every case. So why not translate that into Puppet templates? This module is specific to GridKa, we don't need to be considerate of anybody but ourselves.  
That said, we don't even manage the configuration for our CMS dCache xrootd redirectors through Puppet properly... Mainly because I don't know much about how xrootd has to be configured to do anything in the first place. 😝

**Comment by XMol** [comment]
We also should identify commonalities between the Alice and CMS needs towards this module. Right, @rcaspart?

**Comment by rcaspart** [comment]
Compared to the Alice setup, the CMS one is very simple and has little requirements towards the module. We mainly (and afaik even exclusively) need to be able to run xrootd/cmsd with our own defined configuration.
For starting the services systemd is perfectly fine, and we can even utilize the vanilla systemd service file provided with the xrootd packages, i.e. no requirements for extra functionality here from our side.

**Comment by XMol** [comment]
But the rpms we install do bring their own systemd unit file? For Alice different xrootd rpms are installed, right?

**Comment by maxfischer2781** [comment]
### systemd integration

The ALICE SE uses the rpms from EPEL, which ship with workable ``systemd`` units, and currently adds drop-in files on top.

### configuration

The ALICE xrootd configuration needs ``ofs.authorize``. As far as I can tell, the current ``gridka-xrootd`` template does not support such key-less configuration settings.

**Comment by XMol** [comment]
> The ALICE xrootd configuration needs ofs.authorize. As far as I can tell, the current gridka-xrootd template does not support such key-less configuration settings.

How about an empty value?
```puppet
xrootd::create_config { "/etc/xrootd/xrootd-${title}.cfg":
  params => {
    'ofs.authorize' => '',
  }
}
```
Unless xrootd doesn't like trailing white space, that might work good enough from how I interpret the template...

**Comment by XMol** [comment]
> For starting the services systemd is perfectly fine, and we can even utilize the vanilla systemd service file provided with the xrootd packages (...)

Which systemd files? 😕 
```
[root@cmsxrootd-2 ~]# rpm -qa xrootd
xrootd-4.8.0-2.osg33.el6.x86_64

[root@cmsxrootd-2 ~]# systemctl status xrootd*
● xrootd.service - SYSV: xrootd is a cluster file system.
   Loaded: loaded (/etc/rc.d/init.d/xrootd; bad; vendor preset: disabled)
   Active: active (running) since Wed 2021-02-03 08:31:06 CET; 3 weeks 0 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14809 ExecStop=/etc/rc.d/init.d/xrootd stop (code=exited, status=0/SUCCESS)
  Process: 15061 ExecStart=/etc/rc.d/init.d/xrootd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/xrootd.service
           ├─15146 /usr/bin/xrootd -n cms -c /etc/xrootd/xrootd-cms.cfg -l /var/log/xrootd/cms.xrootd.log -k 200m -b -s /var/run/xrootd/xrootd-cms.pid -n cms
           └─15244 /usr/bin/xrootd -c /etc/xrootd/xrootd-default.cfg -l /var/log/xrootd/default.xrootd.log -k 200m -b -s /var/run/xrootd/xrootd-default.pid -n default
```
Ah, those that are only used on cmsxrootd-1
```
[root@cmsxrootd-1 ~]# systemctl status xrootd*
● xrootd@default.service - XRootD xrootd daemon instance default
   Loaded: loaded (/usr/lib/systemd/system/xrootd@.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-11-10 08:13:53 CET; 3 months 15 days ago
     Docs: man:xrootd(8)
           http://xrootd.org/docs.html
 Main PID: 12204 (xrootd)
   CGroup: /system.slice/system-xrootd.slice/xrootd@default.service
           └─12204 /usr/bin/xrootd -l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd-default.cfg -k fifo -s /var/run/xrootd/xrootd-default.pid -n default

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

● xrootd@cms.service - XRootD xrootd daemon instance cms
   Loaded: loaded (/usr/lib/systemd/system/xrootd@.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-11-10 15:27:39 CET; 3 months 14 days ago
     Docs: man:xrootd(8)
           http://xrootd.org/docs.html
 Main PID: 18471 (xrootd)
   CGroup: /system.slice/system-xrootd.slice/xrootd@cms.service
           └─18471 /usr/bin/xrootd -l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd-cms.cfg -k fifo -s /var/run/xrootd/xrootd-cms.pid -n cms

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

[root@cmsxrootd-1 ~]# rpm -qf /usr/lib/systemd/system/xrootd@.service
xrootd-server-4.12.3-1.osg34.el7.x86_64
```
Not coming from epel though. Sorry, I don't intend to be sassy, you simply inherited a mess from us dCache admins, because we didn't know better, and you have my sincere condolence. 🙏 

I think the best approach would be to merge this and gridka_alice_se into one module. Which means, offer the basic functionality of installing a xrootd package with a comfortable way of supplying the configuration settings, while all the additional plugins and stuff for Alice is covered with additional classes.

**Comment by rcaspart** [comment]
You are right, cmsxrootd-2 is running an older version, and is still relying on the sysV service definitions (although the systemd ones would also be available), and cmsxrootd-1 is running a newer one providing just the systemd unit files (which is also why puppet runs currently fail on this host).
As for the repo, my best guess is that it is installed from osg due to the current setup also relying on the CMS TFC plugin for XRootD.

Anyhow, I hope to be able to clean up at least large parts of this with a new redirector setup, which will be a simple XRootD setup and e.g. no longer require the CMS TFC plugin.
This should then also be very straight forward to have in a common module with the parts required by Alice, as you proposed.

**Comment by XMol** [comment]
Alright, I'll then import gridka_xrootd as a new project to our GitLab an close this GitHub project.
